-- 1
SELECT NAZWISKO, ETAT, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP = (
    SELECT ID_ZESP
    FROM PRACOWNICY
    WHERE NAZWISKO = 'BRZEZINSKI'
)
ORDER BY NAZWISKO;

-- 2
SELECT NAZWISKO, ETAT, NAZWA
FROM PRACOWNICY P
INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP
WHERE P.ID_ZESP = (
    SELECT ID_ZESP
    FROM PRACOWNICY
    WHERE NAZWISKO = 'BRZEZINSKI'
)
ORDER BY NAZWISKO;

-- 3
SELECT NAZWISKO, ETAT, TO_CHAR(ZATRUDNIONY, 'YYYY/MM/DD') AS ZATRUDNIONY
FROM PRACOWNICY
WHERE ZATRUDNIONY = (
    SELECT MIN(ZATRUDNIONY)
    FROM PRACOWNICY
    WHERE ETAT = 'PROFESOR'
)
AND ETAT = 'PROFESOR';

-- 4
SELECT NAZWISKO, TO_CHAR(ZATRUDNIONY, 'YYYY/MM/DD') AS ZATRUDNIONY, ID_ZESP
FROM PRACOWNICY
WHERE (ZATRUDNIONY, ID_ZESP) IN (
    SELECT MAX(ZATRUDNIONY), ID_ZESP
    FROM PRACOWNICY
    GROUP BY ID_ZESP
)
ORDER BY ZATRUDNIONY;

-- 5
SELECT ID_ZESP, NAZWA, ADRES
FROM ZESPOLY
WHERE ID_ZESP IN (
    SELECT ID_ZESP
    FROM ZESPOLY
    MINUS
    SELECT ID_ZESP
    FROM PRACOWNICY
);

-- 6
SELECT NAZWISKO
FROM PRACOWNICY
WHERE ID_PRAC NOT IN (
    SELECT ID_SZEFA
    FROM PRACOWNICY
    WHERE ETAT = 'STAZYSTA'
)
AND ETAT = 'PROFESOR';

-- 7
SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC
FROM PRACOWNICY
GROUP BY ID_ZESP
HAVING SUM(PLACA_POD) IN (
    SELECT MAX(SUMA) AS SUMA_PLAC
    FROM (
        SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA
        FROM PRACOWNICY
        GROUP BY ID_ZESP
    )
);

-- 8
SELECT NAZWA, SUMA_PLAC
FROM (
    SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA_PLAC
    FROM PRACOWNICY
    GROUP BY ID_ZESP
    HAVING SUM(PLACA_POD) IN (
        SELECT MAX(SUMA) AS SUMA_PLAC
        FROM (
            SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA
            FROM PRACOWNICY
            GROUP BY ID_ZESP
        )
    )
) POMOC
INNER JOIN ZESPOLY Z ON POMOC.ID_ZESP = Z.ID_ZESP;

-- 9
SELECT NAZWA, COUNT(NAZWISKO) AS ILU_PRACOWNIKOW
FROM PRACOWNICY P
INNER JOIN ZESPOLY Z ON Z.ID_ZESP = P.ID_ZESP
GROUP BY NAZWA
HAVING COUNT(NAZWISKO) > (
    SELECT COUNT(NAZWISKO)
    FROM PRACOWNICY P
    INNER JOIN ZESPOLY Z ON Z.ID_ZESP = P.ID_ZESP
    WHERE NAZWA LIKE 'ADMINISTRACJA'
);

-- 10
SELECT ETAT
FROM PRACOWNICY P
INNER JOIN ETATY E ON P.ETAT = E.NAZWA
GROUP BY ETAT
HAVING COUNT(ETAT) = (
    SELECT MAX(SUMA)
    FROM (
        SELECT COUNT(ETAT) AS SUMA
        FROM PRACOWNICY
        GROUP BY ETAT
    )
);

-- 11
SELECT ETAT, LISTAGG(NAZWISKO, ',') WITHIN GROUP (ORDER BY NAZWISKO) AS PRACOWNICY
FROM PRACOWNICY P
INNER JOIN ETATY E ON P.ETAT = E.NAZWA
GROUP BY ETAT
HAVING COUNT(ETAT) = (
    SELECT MAX(SUMA)
    FROM (
        SELECT COUNT(ETAT) AS SUMA
        FROM PRACOWNICY
        GROUP BY ETAT
    )
);

-- 12
SELECT P.NAZWISKO AS PRACOWNIK, S.NAZWISKO AS SZEF
FROM PRACOWNICY P
INNER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
WHERE ABS(S.PLACA_POD - P.PLACA_POD) = (
    SELECT MIN(ABS(S.PLACA_POD - P.PLACA_POD))
    FROM PRACOWNICY P
    INNER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
);
