-- 1.
INSERT INTO PRACOWNICY VALUES(250, 'KOWALSKI', 'ASYSTENT', NULL, DATE '2015-01-13', 1500, NULL, 10);
INSERT INTO PRACOWNICY VALUES(260, 'ADAMSKI', 'ASYSTENT', NULL, DATE '2014-09-10', 1500, NULL, 10);
INSERT INTO PRACOWNICY VALUES(270, 'NOWAK', 'ADIUNKT', NULL, DATE '1990-05-01', 2050, 540, 20);

SELECT * FROM PRACOWNICY WHERE ID_PRAC >= 250;

-- 2.
UPDATE PRACOWNICY
SET PLACA_POD = PLACA_POD * 1.1,
    PLACA_DOD = COALESCE(PLACA_DOD * 1.2, 100)
WHERE ID_PRAC >= 250;

-- 3.
INSERT INTO ZESPOLY VALUES(60, 'BAZY DANYCH', 'PIOTROWO 2');
SELECT * FROM ZESPOLY;

-- 4.
UPDATE PRACOWNICY SET ID_ZESP = 60 WHERE ID_PRAC >= 250;
SELECT * FROM PRACOWNICY;

-- 5.
UPDATE PRACOWNICY
SET ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY')
WHERE ID_ZESP = 60;

SELECT * FROM PRACOWNICY WHERE ID_SZEFA = (SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY');

-- 6.
DELETE FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH';

-- 7.
DELETE FROM PRACOWNICY WHERE ID_ZESP = 60;
DELETE FROM ZESPOLY WHERE NAZWA = 'BAZY DANYCH';

-- 8.
SELECT NAZWISKO, PLACA_POD, PODWYZKA
FROM PRACOWNICY P
INNER JOIN (
    SELECT ID_ZESP, AVG(PLACA_POD)*0.1 AS PODWYZKA
    FROM PRACOWNICY
    GROUP BY ID_ZESP
) A ON P.ID_ZESP = A.ID_ZESP
ORDER BY NAZWISKO;

-- 9.
UPDATE PRACOWNICY C
SET PLACA_POD = (
    SELECT PODWYZKA + PLACA_POD
    FROM PRACOWNICY P
    INNER JOIN (
        SELECT ID_ZESP, AVG(PLACA_POD)*0.1 AS PODWYZKA
        FROM PRACOWNICY
        GROUP BY ID_ZESP
    ) A ON P.ID_ZESP = A.ID_ZESP
    WHERE C.NAZWISKO = P.NAZWISKO
);

SELECT NAZWISKO, PLACA_POD FROM PRACOWNICY ORDER BY NAZWISKO;

-- 10.
SELECT * FROM PRACOWNICY WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

-- 11.
UPDATE PRACOWNICY
SET PLACA_POD = (SELECT ROUND(AVG(PLACA_POD), 2) FROM PRACOWNICY)
WHERE PLACA_POD = (SELECT MIN(PLACA_POD) FROM PRACOWNICY);

-- 12.
UPDATE PRACOWNICY C
SET PLACA_DOD = (
    SELECT AVG(PLACA_POD) FROM PRACOWNICY
    WHERE ID_SZEFA = (
        SELECT ID_PRAC FROM PRACOWNICY WHERE NAZWISKO = 'MORZY'
    )
)
WHERE ID_ZESP = 20;

-- 13.
UPDATE (
    SELECT NAZWISKO, PLACA_POD, NAZWA
    FROM PRACOWNICY NATURAL JOIN ZESPOLY
    WHERE NAZWA = 'SYSTEMY ROZPROSZONE'
)
SET PLACA_POD = PLACA_POD * 1.25;

-- 14.
DELETE FROM (
    SELECT P.NAZWISKO AS PRACOWNIK, S.NAZWISKO AS SZEF
    FROM PRACOWNICY P JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
)
WHERE SZEF = 'MORZY';

-- 15.
SELECT * FROM PRACOWNICY ORDER BY NAZWISKO;

-- 16.
CREATE SEQUENCE PRAC_SEQ START WITH 300 INCREMENT BY 10;

-- 17.
INSERT INTO PRACOWNICY(ID_PRAC, NAZWISKO, PLACA_POD)
VALUES(PRAC_SEQ.NEXTVAL, 'TRABCZYNSKI', 1000);

-- 18.
UPDATE PRACOWNICY SET PLACA_DOD = PRAC_SEQ.CURRVAL WHERE NAZWISKO = 'TRABCZYNSKI';

-- 19.
DELETE FROM PRACOWNICY WHERE NAZWISKO = 'TRABCZYNSKI';

-- 20.
CREATE SEQUENCE MALA_SEQ START WITH 9 INCREMENT BY 1 MAXVALUE 10;

-- 21.
DROP SEQUENCE MALA_SEQ;
