-- 1.1
SELECT NAZWISKO, PLACA_POD
FROM PRACOWNICY
ORDER BY PLACA_POD DESC
FETCH FIRST 3 ROWS ONLY;

-- 1.2
SELECT NAZWISKO, PLACA_POD
FROM (
    SELECT ROWNUM, NAZWISKO, PLACA_POD
    FROM PRACOWNICY
    ORDER BY PLACA_POD DESC
)
WHERE ROWNUM <= 3;

-- 2.1
SELECT NAZWISKO, PLACA_POD
FROM PRACOWNICY
ORDER BY PLACA_POD DESC
OFFSET 5 ROWS
FETCH NEXT 5 ROWS ONLY;

-- 2.2
SELECT NAZWISKO, PLACA_POD
FROM (
    SELECT ROWNUM AS NUMER, NAZWISKO, PLACA_POD
    FROM (
        SELECT NAZWISKO, PLACA_POD
        FROM PRACOWNICY
        ORDER BY PLACA_POD DESC  
    )
)
WHERE NUMER BETWEEN 6 AND 10;

-- 3
WITH SREDNIA_ZESP AS (
    SELECT ID_ZESP, AVG(PLACA_POD) AS SREDNIA
    FROM PRACOWNICY
    GROUP BY ID_ZESP
)
SELECT P.NAZWISKO, P.PLACA_POD, P.PLACA_POD - S.SREDNIA AS ROZNICA
FROM PRACOWNICY P
INNER JOIN SREDNIA_ZESP S ON S.ID_ZESP = P.ID_ZESP
WHERE P.PLACA_POD - S.SREDNIA > 0;

-- 4
WITH LATA AS (
    SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS LICZBA
    FROM PRACOWNICY
    GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
)
SELECT * FROM LATA
ORDER BY LICZBA DESC;

-- 5
WITH LATA AS (
    SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS LICZBA
    FROM PRACOWNICY
    GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
)
SELECT * FROM LATA
ORDER BY LICZBA DESC
FETCH FIRST 1 ROWS ONLY;

-- 6
WITH ASYSTENCI AS (
    SELECT ID_PRAC, NAZWISKO, ETAT, ID_ZESP
    FROM PRACOWNICY
    WHERE ETAT = 'ASYSTENT'
),
PIOTROWO AS (
    SELECT P.ID_PRAC, P.ID_ZESP, Z.NAZWA, Z.ADRES
    FROM PRACOWNICY P
    INNER JOIN ZESPOLY Z ON P.ID_ZESP = Z.ID_ZESP
    WHERE Z.ADRES = 'PIOTROWO 3A'
)
SELECT A.NAZWISKO, A.ETAT, PI.NAZWA, PI.ADRES
FROM ASYSTENCI A
INNER JOIN PIOTROWO PI ON A.ID_PRAC = PI.ID_PRAC;

-- 7
WITH SUMY AS (
    SELECT ID_ZESP, SUM(PLACA_POD) AS MAKS_SUMA_PLAC
    FROM PRACOWNICY
    GROUP BY ID_ZESP
)
SELECT Z.NAZWA, S.MAKS_SUMA_PLAC
FROM ZESPOLY Z
INNER JOIN SUMY S ON Z.ID_ZESP = S.ID_ZESP
ORDER BY S.MAKS_SUMA_PLAC DESC
FETCH FIRST 1 ROWS ONLY;

-- 8.1
WITH podwladni (id_prac, id_szefa, nazwisko, poziom) AS (
    SELECT id_prac, id_szefa, nazwisko, 1
    FROM pracownicy
    WHERE nazwisko = 'BRZEZINSKI'
    UNION ALL
    SELECT p.id_prac, p.id_szefa, p.nazwisko, poziom + 1
    FROM podwladni s
    JOIN pracownicy p ON s.id_prac = p.id_szefa
)
SEARCH DEPTH FIRST BY nazwisko SET porzadek_potomkow
SELECT nazwisko, poziom AS POZYCJA_W_HIERARCHII
FROM podwladni
ORDER BY porzadek_potomkow;

-- 8.2
SELECT nazwisko, LEVEL AS poziom
FROM pracownicy
CONNECT BY id_szefa = PRIOR id_prac
START WITH nazwisko = 'BRZEZINSKI'
ORDER SIBLINGS BY nazwisko;

-- 9.1
WITH podwladni (id_prac, id_szefa, nazwisko, poziom) AS (
    SELECT id_prac, id_szefa, nazwisko, 1
    FROM pracownicy
    WHERE nazwisko = 'BRZEZINSKI'
    UNION ALL
    SELECT p.id_prac, p.id_szefa, p.nazwisko, poziom + 1
    FROM podwladni s
    JOIN pracownicy p ON s.id_prac = p.id_szefa
)
SEARCH DEPTH FIRST BY nazwisko SET porzadek_potomkow
SELECT LPAD(' ', poziom - 1, ' ') || nazwisko AS NAZWISKO, poziom AS POZYCJA_W_HIERARCHII
FROM podwladni
ORDER BY porzadek_potomkow;

-- 9.2
SELECT n AS nazwisko, poziom
FROM (
    SELECT LPAD(' ', LEVEL - 1, ' ') || nazwisko AS n, LEVEL AS poziom
    FROM pracownicy
    CONNECT BY id_szefa = PRIOR id_prac
    START WITH nazwisko = 'BRZEZINSKI'
    ORDER SIBLINGS BY nazwisko
);
