-- 1
SELECT MIN(PLACA_POD) AS MINIMUM,
       MAX(PLACA_POD) AS MAKSIMUM,
       MAX(PLACA_POD) - MIN(PLACA_POD) AS ROZNICA
FROM PRACOWNICY;

-- 2
SELECT ETAT,
       AVG(PLACA_POD) AS SREDNIA
FROM PRACOWNICY
GROUP BY ETAT
ORDER BY SREDNIA DESC;

-- 3
SELECT COUNT(*) AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT LIKE 'PROFESOR';

-- 4
SELECT ID_ZESP,
       SUM(PLACA_POD) + SUM(PLACA_DOD) AS SUMARYCZNE_PLACE
FROM PRACOWNICY
GROUP BY ID_ZESP
ORDER BY ID_ZESP;

-- 5
SELECT MAX(SUM(PLACA_POD) + SUM(PLACA_DOD)) AS MAKS_SUM_PLACA
FROM PRACOWNICY
GROUP BY ID_ZESP;

-- 6
SELECT ID_SZEFA,
       MIN(PLACA_POD) AS MINIMALNA
FROM PRACOWNICY
WHERE ID_SZEFA IS NOT NULL
GROUP BY ID_SZEFA
ORDER BY MINIMALNA DESC;

-- 7
SELECT ID_ZESP,
       COUNT(*) AS ILU_PRACUJE
FROM PRACOWNICY
GROUP BY ID_ZESP;

-- 8
SELECT ID_ZESP,
       COUNT(*) AS ILU_PRACUJE
FROM PRACOWNICY
GROUP BY ID_ZESP
HAVING COUNT(*) > 3;

-- 9
SELECT ID_PRAC
FROM PRACOWNICY
GROUP BY ID_PRAC
HAVING COUNT(*) > 1;

-- 10
SELECT ETAT,
       AVG(PLACA_POD) AS ŚREDNIA,
       COUNT(*) AS LICZBA
FROM PRACOWNICY
WHERE ZATRUDNIONY < DATE '1990-01-01'
GROUP BY ETAT
ORDER BY ETAT;

-- 11
SELECT ID_ZESP,
       ETAT,
       ROUND(AVG(PLACA_POD) + AVG(COALESCE(PLACA_DOD, 0))) AS SREDNIA,
       ROUND(MAX(PLACA_POD + COALESCE(PLACA_DOD, 0))) AS MAKSYMALNA
FROM PRACOWNICY
WHERE ETAT IN ('ASYSTENT', 'PROFESOR')
GROUP BY ID_ZESP, ETAT
ORDER BY ID_ZESP, ETAT;

-- 12
SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK,
       COUNT(*) AS ILU_PRACOWNIKOW
FROM PRACOWNICY
GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
ORDER BY ROK;

-- 13
SELECT LENGTH(NAZWISKO) AS ILE_LITER,
       COUNT(*) AS W_ILU_NAZWISKACH
FROM PRACOWNICY
GROUP BY LENGTH(NAZWISKO)
ORDER BY ILE_LITER;

-- 14
SELECT COUNT(*) AS ILE_NAZWISK_Z_A
FROM PRACOWNICY
WHERE NAZWISKO LIKE '%A%'
   OR NAZWISKO LIKE '%a%';

-- 15
SELECT DISTINCT
       (SELECT COUNT(*)
        FROM PRACOWNICY
        WHERE NAZWISKO LIKE '%A%'
           OR NAZWISKO LIKE '%a%') AS ILE_NAZWISK_Z_A,
       (SELECT COUNT(*)
        FROM PRACOWNICY
        WHERE NAZWISKO LIKE '%E%'
           OR NAZWISKO LIKE '%e%') AS ILE_NAZWISK_Z_E
FROM PRACOWNICY;

-- 16
SELECT ID_ZESP,
       SUM(PLACA_POD) AS SUMA_PLAC,
       LISTAGG(NAZWISKO || ':' || PLACA_POD, ';')
           WITHIN GROUP (ORDER BY NAZWISKO) AS PRACOWNICY
FROM PRACOWNICY
GROUP BY ID_ZESP
ORDER BY ID_ZESP;
