-- 1
SELECT *
FROM ZESPOLY
ORDER BY ID_ZESP;

-- 2
SELECT *
FROM PRACOWNICY
ORDER BY ID_PRAC;

-- 3
SELECT NAZWISKO, 12 * PLACA_POD AS ROCZNA_PLACA
FROM PRACOWNICY
ORDER BY NAZWISKO;

-- 4
SELECT NAZWISKO, ETAT, PLACA_POD + COALESCE(PLACA_DOD, 0) AS MIESIECZNE_ZAROBKI
FROM PRACOWNICY
ORDER BY MIESIECZNE_ZAROBKI DESC;

-- 5
SELECT *
FROM ZESPOLY
ORDER BY NAZWA;

-- 6
SELECT DISTINCT ETAT
FROM PRACOWNICY
ORDER BY ETAT;

-- 7
SELECT *
FROM PRACOWNICY
WHERE ETAT LIKE 'ASYSTENT'
ORDER BY NAZWISKO;

-- 8
SELECT ID_PRAC, NAZWISKO, ETAT, PLACA_POD, ID_ZESP
FROM PRACOWNICY
WHERE ID_ZESP IN (30, 40)
ORDER BY PLACA_POD DESC;

-- 9
SELECT NAZWISKO, ID_ZESP, PLACA_POD
FROM PRACOWNICY
WHERE PLACA_POD BETWEEN 300 AND 800
ORDER BY NAZWISKO;

-- 10
SELECT NAZWISKO, ETAT, ID_ZESP
FROM PRACOWNICY
WHERE NAZWISKO LIKE '%SKI'
ORDER BY NAZWISKO;

-- 11
SELECT ID_PRAC, ID_SZEFA, NAZWISKO, PLACA_POD
FROM PRACOWNICY
WHERE PLACA_POD > 1000 AND ID_SZEFA IS NOT NULL
ORDER BY NAZWISKO;

-- 12
SELECT NAZWISKO, ID_ZESP
FROM PRACOWNICY
WHERE (NAZWISKO LIKE '%SKI' OR NAZWISKO LIKE 'M%')
  AND ID_ZESP = 20
ORDER BY NAZWISKO;

-- 13
SELECT NAZWISKO, ETAT, CAST(PLACA_POD / (20 * 8) AS NUMERIC(10,4)) AS STAWKA
FROM PRACOWNICY
WHERE ETAT NOT IN ('STAZYSTA', 'ADIUNKT', 'ASYSTENT')
  AND PLACA_POD NOT BETWEEN 400 AND 800
ORDER BY STAWKA;

-- 14
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_DOD
FROM PRACOWNICY
WHERE (PLACA_POD + COALESCE(PLACA_DOD, 0)) > 1000
ORDER BY ETAT, NAZWISKO;

-- 15
SELECT NAZWISKO || ' PRACUJE OD ' || ZATRUDNIONY || ' I ZARABIA ' || PLACA_POD AS PROFESOROWIE
FROM PRACOWNICY
WHERE ETAT LIKE 'PROFESOR'
ORDER BY PLACA_POD DESC;
