-- 1
SELECT ID_ZESP, NAZWA, ADRES
FROM ZESPOLY Z
WHERE NOT EXISTS (
    SELECT * FROM PRACOWNICY P WHERE Z.ID_ZESP = P.ID_ZESP
);

-- 2
SELECT NAZWISKO, PLACA_POD, ETAT
FROM PRACOWNICY P
WHERE PLACA_POD > (
    SELECT AVG(PLACA_POD)
    FROM PRACOWNICY
    WHERE ETAT = P.ETAT
)
ORDER BY PLACA_POD DESC;

-- 3
SELECT NAZWISKO, PLACA_POD
FROM PRACOWNICY P
WHERE PLACA_POD > (
    SELECT PLACA_POD * 0.75
    FROM PRACOWNICY
    WHERE P.ID_SZEFA = ID_PRAC
)
ORDER BY NAZWISKO;

-- 4
SELECT NAZWISKO
FROM PRACOWNICY P
WHERE NOT EXISTS (
    SELECT ETAT
    FROM PRACOWNICY
    WHERE ETAT = 'STAZYSTA'
      AND ID_SZEFA = P.ID_PRAC
)
AND P.ETAT = 'PROFESOR';

-- 5
SELECT Z.NAZWA, MAKS_SUMA_PLAC
FROM (
    SELECT MAX(SUM(PLACA_POD)) AS MAKS_SUMA_PLAC
    FROM PRACOWNICY
    GROUP BY ID_ZESP
) M,
(
    SELECT ID_ZESP, SUM(PLACA_POD) AS SUMA
    FROM PRACOWNICY
    GROUP BY ID_ZESP
) S,
ZESPOLY Z
WHERE SUMA = MAKS_SUMA_PLAC
  AND Z.ID_ZESP = S.ID_ZESP;

-- 6
SELECT NAZWISKO, PLACA_POD
FROM PRACOWNICY P
WHERE 3 > (
    SELECT COUNT(PLACA_POD)
    FROM PRACOWNICY
    WHERE P.PLACA_POD < PLACA_POD
);

-- 7
SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS LICZBA
FROM PRACOWNICY
GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
ORDER BY LICZBA DESC, ROK;

-- 8
SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS LICZBA
FROM PRACOWNICY
GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
HAVING COUNT(*) = (
    SELECT MAX(LICZBAHELP)
    FROM (
        SELECT EXTRACT(YEAR FROM ZATRUDNIONY) AS ROK, COUNT(*) AS LICZBAHELP
        FROM PRACOWNICY
        GROUP BY EXTRACT(YEAR FROM ZATRUDNIONY)
        ORDER BY LICZBAHELP DESC, ROK
    )
);

-- 9.1
SELECT NAZWISKO, PLACA_POD, PLACA_POD - SREDNIA AS ROZNICA
FROM PRACOWNICY P,
(
    SELECT ID_ZESP, AVG(PLACA_POD) AS SREDNIA
    FROM PRACOWNICY
    GROUP BY ID_ZESP
) H
WHERE H.ID_ZESP = P.ID_ZESP
ORDER BY NAZWISKO;

-- 9.2
SELECT NAZWISKO, PLACA_POD,
       PLACA_POD - (
           SELECT AVG(PLACA_POD)
           FROM PRACOWNICY
           WHERE ID_ZESP = P.ID_ZESP
       ) AS ROZNICA
FROM PRACOWNICY P
ORDER BY NAZWISKO;

-- 10.1
SELECT NAZWISKO, PLACA_POD, PLACA_POD - SREDNIA AS ROZNICA
FROM PRACOWNICY P,
(
    SELECT ID_ZESP, AVG(PLACA_POD) AS SREDNIA
    FROM PRACOWNICY
    GROUP BY ID_ZESP
) H
WHERE H.ID_ZESP = P.ID_ZESP
  AND PLACA_POD - SREDNIA > 0
ORDER BY NAZWISKO;

-- 10.2
SELECT NAZWISKO, PLACA_POD,
       PLACA_POD - (
           SELECT AVG(PLACA_POD)
           FROM PRACOWNICY
           WHERE ID_ZESP = P.ID_ZESP
       ) AS ROZNICA
FROM PRACOWNICY P
WHERE PLACA_POD - (
        SELECT AVG(PLACA_POD)
        FROM PRACOWNICY
        WHERE ID_ZESP = P.ID_ZESP
      ) > 0
ORDER BY NAZWISKO;

-- 11
SELECT NAZWISKO, PODWLADNI
FROM PRACOWNICY P
INNER JOIN ZESPOLY Z USING (ID_ZESP),
(
    SELECT ID_SZEFA, COUNT(ID_PRAC) AS PODWLADNI
    FROM PRACOWNICY
    WHERE ID_SZEFA IS NOT NULL
    GROUP BY ID_SZEFA
) H
WHERE ETAT = 'PROFESOR'
  AND ADRES = 'PIOTROWO 3A'
  AND H.ID_SZEFA = P.ID_PRAC;

-- 12
SELECT NAZWA, SREDNIA_W_ZESPOLE, SREDNIA_OGOLNA,
CASE
    WHEN SREDNIA_W_ZESPOLE IS NULL THEN '???'
    WHEN SREDNIA_W_ZESPOLE > SREDNIA_OGOLNA THEN ':)'
    WHEN SREDNIA_W_ZESPOLE < SREDNIA_OGOLNA THEN ':('
    WHEN SREDNIA_W_ZESPOLE = SREDNIA_OGOLNA THEN ':|'
END AS NASTROJE
FROM (
    SELECT NAZWA,
           AVG(PLACA_POD) AS SREDNIA_W_ZESPOLE,
           (SELECT AVG(PLACA_POD) FROM PRACOWNICY) AS SREDNIA_OGOLNA
    FROM ZESPOLY Z
    LEFT JOIN PRACOWNICY P ON Z.ID_ZESP = P.ID_ZESP
    GROUP BY NAZWA
) POMOC;

-- 13
SELECT NAZWA, PLACA_MIN, PLACA_MAX
FROM ETATY E
ORDER BY (
    SELECT COUNT(*)
    FROM PRACOWNICY
    WHERE E.NAZWA = ETAT
) ASC, NAZWA DESC;
