-- 1
SELECT NAZWISKO, ETAT, PRACOWNICY.ID_ZESP, NAZWA
FROM PRACOWNICY
INNER JOIN ZESPOLY ON PRACOWNICY.ID_ZESP = ZESPOLY.ID_ZESP
ORDER BY NAZWISKO;

-- 2
SELECT NAZWISKO, ETAT, PRACOWNICY.ID_ZESP, NAZWA
FROM PRACOWNICY
INNER JOIN ZESPOLY ON PRACOWNICY.ID_ZESP = ZESPOLY.ID_ZESP
WHERE ADRES = 'PIOTROWO 3A'
ORDER BY NAZWISKO;

-- 3
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX
FROM PRACOWNICY
INNER JOIN ETATY ON ETAT = NAZWA
ORDER BY ETAT, NAZWISKO;

-- 4
SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX,
       CASE
           WHEN PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX THEN 'OK'
           ELSE 'NIE'
       END AS CZY_PENSJA_OK
FROM PRACOWNICY
INNER JOIN ETATY ON ETAT = NAZWA
ORDER BY ETAT, NAZWISKO;

-- 5
SELECT *
FROM (
    SELECT NAZWISKO, ETAT, PLACA_POD, PLACA_MIN, PLACA_MAX,
           CASE
               WHEN PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX THEN 'OK'
               ELSE 'NIE'
           END AS CZY_PENSJA_OK
    FROM PRACOWNICY
    INNER JOIN ETATY ON ETAT = NAZWA
)
WHERE CZY_PENSJA_OK = 'NIE'
ORDER BY ETAT, NAZWISKO;

-- 6
SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX
FROM PRACOWNICY
INNER JOIN ETATY ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX
ORDER BY NAZWISKO, KAT_PLAC;

-- 7
SELECT NAZWISKO, PLACA_POD, ETAT, NAZWA AS KAT_PLAC, PLACA_MIN, PLACA_MAX
FROM PRACOWNICY
INNER JOIN ETATY ON PLACA_POD BETWEEN PLACA_MIN AND PLACA_MAX
WHERE NAZWA = 'SEKRETARKA'
ORDER BY NAZWISKO;

-- 8
SELECT P.NAZWISKO AS PRACOWNIK, P.ID_PRAC, S.NAZWISKO AS SZEF, P.ID_SZEFA
FROM PRACOWNICY P
INNER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
ORDER BY P.NAZWISKO;

-- 9
SELECT P.NAZWISKO AS PRACOWNIK, P.ZATRUDNIONY AS PRAC_ZATRUDNIONY,
       S.NAZWISKO AS SZEF, S.ZATRUDNIONY AS SZEF_ZATRUDNIONY,
       EXTRACT(YEAR FROM P.ZATRUDNIONY) - EXTRACT(YEAR FROM S.ZATRUDNIONY) AS LATA
FROM PRACOWNICY P
INNER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC
WHERE EXTRACT(YEAR FROM P.ZATRUDNIONY) - EXTRACT(YEAR FROM S.ZATRUDNIONY) < 10
ORDER BY PRAC_ZATRUDNIONY, PRACOWNIK;

-- 10
SELECT NAZWA,
       COUNT(NAZWA) AS LICZBA_PRACOWNIKOW,
       AVG(PLACA_POD) AS SREDNIA_PLACA
FROM PRACOWNICY
INNER JOIN ZESPOLY ON PRACOWNICY.ID_ZESP = ZESPOLY.ID_ZESP
GROUP BY NAZWA
ORDER BY NAZWA;

-- 11
SELECT NAZWA,
       COUNT(NAZWA) AS LICZBA_PRACOWNIKOW,
       CASE
           WHEN COUNT(NAZWA) BETWEEN 0 AND 2 THEN 'mały'
           WHEN COUNT(NAZWA) BETWEEN 3 AND 6 THEN 'średni'
           WHEN COUNT(NAZWA) >= 7 THEN 'duży'
       END AS ETYKIETA
FROM PRACOWNICY
INNER JOIN ZESPOLY ON PRACOWNICY.ID_ZESP = ZESPOLY.ID_ZESP
GROUP BY NAZWA
ORDER BY NAZWA;
