-- 1.
CREATE TABLE PROJEKTY (
    ID_PROJEKTU NUMBER(4) GENERATED ALWAYS AS IDENTITY,
    OPIS_PROJEKTU VARCHAR(20),
    DATA_ROZPOCZECIA DATE DEFAULT CURRENT_DATE,
    DATA_ZAKONCZENIA DATE,
    FUNDUSZ NUMBER(7,2)
);

-- 2.
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('INDEKSY BITMAPOWE', DATE '1999-04-02', DATE '2001-08-31', 25000);
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('SIECI KREGOSLUPOWE', NULL, 19000);

-- 3.
SELECT ID_PROJEKTU, OPIS_PROJEKTU
FROM PROJEKTY;

-- 4.
INSERT INTO PROJEKTY (ID_PROJEKTU, OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES (10, 'INDEKSY DRZEWIASTE', DATE '2013-12-24', DATE '2014-01-01', 1200);
-- NIEPOWODZENIE, BO:
-- ORA-32795: nie można wstawić do kolumny tożsamości utworzonej jako GENERATED ALWAYS
INSERT INTO PROJEKTY (OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES ('INDEKSY DRZEWIASTE', DATE '2013-12-24', DATE '2014-01-01', 1200);

-- 5.
UPDATE PROJEKTY
SET ID_PROJEKTU = 10
WHERE OPIS_PROJEKTU = 'INDEKSY DRZEWIASTE';
-- NIEPOWODZENIE, BO:
-- ORA-32796: nie można zaktualizować kolumny tożsamości utworzonej jako GENERATED ALWAYS

-- 6.
CREATE TABLE PROJEKTY_KOPIA AS
(SELECT * FROM PROJEKTY);
SELECT * FROM PROJEKTY_KOPIA;

-- 7.
INSERT INTO PROJEKTY_KOPIA (ID_PROJEKTU, OPIS_PROJEKTU, DATA_ROZPOCZECIA, DATA_ZAKONCZENIA, FUNDUSZ)
VALUES (10, 'SIECI LOKALNE', CURRENT_DATE, CURRENT_DATE + INTERVAL '1' YEAR, 1200);
SELECT * FROM PROJEKTY_KOPIA;
-- POWIODŁO SIĘ, BO KOPIA TABELI NIE ZACHOWAŁA ATRYBUTU GENERATE ALWAYS.
-- MOŻNA TO SPRAWDZIĆ POLECENIEM
-- DESCRIBE PROJEKTY_KOPIA;

-- 8.
DELETE FROM PROJEKTY
WHERE OPIS_PROJEKTU = 'INDEKSY DRZEWIASTE';
SELECT * FROM PROJEKTY;
SELECT * FROM PROJEKTY_KOPIA;
-- POLECENIE, NIE USUWA TEGO REKORDU Z KOPII, BO TO SĄ ZUPEŁNIE DWIE OSOBNE TABELE.

-- 9.
SELECT TABLE_NAME
FROM TABS
ORDER BY TABLE_NAME;
