-- 1.
CREATE OR REPLACE VIEW ASYSTENCI(
    ID, NAZWISKO, PLACA, STAZ
) AS SELECT
    ID_PRAC,
    NAZWISKO,
    PLACA_POD + COALESCE(PLACA_DOD, 0),
    'LAT: ' || TO_CHAR(EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM ZATRUDNIONY) - 1)  || ' MIESIECY: ' || TO_CHAR(12 - EXTRACT(MONTH FROM ZATRUDNIONY))
FROM PRACOWNICY
WHERE ETAT = 'ASYSTENT';

SELECT * FROM ASYSTENCI ORDER BY NAZWISKO;

-- 2.
CREATE OR REPLACE VIEW PLACE(
    ID_ZESP, SREDNIA, MINIMUM, MAKSIMUM, FUNDUSZ, L_PENCJI, L_DODATKOW
) AS SELECT
    ID_ZESP,
    AVG(PLACA_POD+COALESCE(PLACA_DOD,0)),
    MIN(PLACA_POD+COALESCE(PLACA_DOD,0)),
    MAX(PLACA_POD+COALESCE(PLACA_DOD,0)),
    SUM(PLACA_POD+COALESCE(PLACA_DOD,0)),
    COUNT(PLACA_POD),
    COUNT(PLACA_DOD)
FROM PRACOWNICY
GROUP BY ID_ZESP;

SELECT * FROM PLACE ORDER BY ID_ZESP;

-- 3.
SELECT NAZWISKO, PLACA_POD, SREDNIA, ID_ZESP
FROM PRACOWNICY NATURAL JOIN PLACE
WHERE PLACA_POD < SREDNIA
ORDER BY NAZWISKO;

-- 4.
CREATE OR REPLACE VIEW PLACE_MINIMALNE(
    ID_PRAC, NAZWISKO, ETAT, PLACA_POD
) AS SELECT
    ID_PRAC,
    NAZWISKO,
    ETAT,
    PLACA_POD
FROM PRACOWNICY
WHERE PLACA_POD < 700
WITH CHECK OPTION CONSTRAINT ZA_DUZA_PLACA;

SELECT * FROM PLACE_MINIMALNE
ORDER BY NAZWISKO;

-- 5.
UPDATE PLACE_MINIMALNE
SET PLACA_POD = 800
WHERE NAZWISKO = 'HAPKE';

-- 6.
CREATE OR REPLACE VIEW PRAC_SZEF (
    ID_PRAC, ID_SZEFA, PRACOWNIK, ETAT, SZEF
) AS SELECT
    P.ID_PRAC,
    P.ID_SZEFA,
    P.NAZWISKO,
    P.ETAT,
    S.NAZWISKO
FROM PRACOWNICY P INNER JOIN PRACOWNICY S ON P.ID_SZEFA = S.ID_PRAC;

INSERT INTO PRAC_SZEF (ID_PRAC, ID_SZEFA, PRACOWNIK, ETAT)
VALUES (280, 150, 'MORZY', 'ASYSTENT');

UPDATE PRAC_SZEF
SET ID_SZEFA = 130
WHERE ID_PRAC = 280;

DELETE FROM PRAC_SZEF
WHERE ID_PRAC = 280;

-- 7.
CREATE OR REPLACE VIEW ZAROBKI (
    ID_PRAC, NAZWISKO, ETAT, PLACA_POD
) AS SELECT
    ID_PRAC,
    NAZWISKO,
    ETAT,
    PLACA_POD
FROM PRACOWNICY P
WHERE PLACA_POD <=
    (SELECT PLACA_POD
    FROM PRACOWNICY
    WHERE ID_PRAC = P.ID_SZEFA)
WITH CHECK OPTION CONSTRAINT SZEF_BOGATSZY;

SELECT * FROM ZAROBKI
ORDER BY NAZWISKO;

UPDATE ZAROBKI
SET PLACA_POD = 2000
WHERE NAZWISKO = 'BIALY';

-- 8.
SELECT COLUMN_NAME, UPDATABLE, INSERTABLE, DELETABLE
FROM USER_UPDATABLE_COLUMNS
WHERE TABLE_NAME = 'PRAC_SZEF';
